/**
 * MESA DAS SOMBRAS — Banco de Dados D&D 5e Oficial
 * Extraído de: Livro do Jogador, Guia do Mestre,
 * Manual dos Monstros, Guia de Xanathar
 */

const DND5E = {
  racas: [
    {nome:'Humano',bonus_atributos:{for:1,des:1,con:1,int:1,sab:1,car:1},tamanho:'Médio',deslocamento:9,tracos:['Proficiência extra ou talento'],idiomas:['Comum','Um à escolha']},
    {nome:'Elfo (Alto)',bonus_atributos:{des:2,int:1},tamanho:'Médio',deslocamento:9,tracos:['Visão no Escuro 18m','Sentidos Aguçados','Linhagem Feérica','Transe 4h','Truque Arcano'],proficiencias:['Espadas longas','Arcos longos'],resistencias:['enfeitiçado'],idiomas:['Comum','Élfico']},
    {nome:'Elfo (da Floresta)',bonus_atributos:{des:2,sab:1},tamanho:'Médio',deslocamento:10.5,tracos:['Visão no Escuro 18m','Furtividade Natural','Magia das Profundezas'],idiomas:['Comum','Élfico']},
    {nome:'Anão (da Colina)',bonus_atributos:{con:2,sab:1},tamanho:'Médio',deslocamento:7.5,tracos:['Visão no Escuro 18m','Resiliência Anã','Tenacidade +1PV/nível'],resistencias:['veneno'],idiomas:['Comum','Anão']},
    {nome:'Anão (da Montanha)',bonus_atributos:{for:2,con:2},tamanho:'Médio',deslocamento:7.5,tracos:['Visão no Escuro 18m','Resiliência Anã','Proficiência Armaduras'],resistencias:['veneno'],idiomas:['Comum','Anão']},
    {nome:'Halfling (Pés Leves)',bonus_atributos:{des:2,car:1},tamanho:'Pequeno',deslocamento:7.5,tracos:['Sortudo','Corajoso','Furtividade Natural'],idiomas:['Comum','Halfling']},
    {nome:'Meio-Elfo',bonus_atributos:{car:2},bonus_extra:'+1 em dois à escolha',tamanho:'Médio',deslocamento:9,tracos:['Visão no Escuro 18m','Linhagem Feérica','2 perícias à escolha'],idiomas:['Comum','Élfico','Um à escolha']},
    {nome:'Meio-Orc',bonus_atributos:{for:2,con:1},tamanho:'Médio',deslocamento:9,tracos:['Visão no Escuro 18m','Intimidação','Resistência Implacável','Ataques Selvagens'],idiomas:['Comum','Orc']},
    {nome:'Tiefling',bonus_atributos:{int:1,car:2},tamanho:'Médio',deslocamento:9,tracos:['Visão no Escuro 18m','Resistência ao Fogo','Legado Infernal'],idiomas:['Comum','Infernal']},
    {nome:'Draconato',bonus_atributos:{for:2,car:1},tamanho:'Médio',deslocamento:9,tracos:['Ancestralidade Dracônica','Sopro Dracônico','Resistência elemental'],idiomas:['Comum','Dracônico']},
    {nome:'Gnomo (das Florestas)',bonus_atributos:{int:2,des:1},tamanho:'Pequeno',deslocamento:7.5,tracos:['Visão no Escuro 18m','Astúcia Gnômica','Ilusionismo Natural'],idiomas:['Comum','Gnômico']},
    {nome:'Halfling (Robusto)',bonus_atributos:{des:2,con:1},tamanho:'Pequeno',deslocamento:7.5,tracos:['Sortudo','Corajoso','Resistência Robusta'],idiomas:['Comum','Halfling']},
  ],

  classes: [
    {nome:'Bárbaro',dado_vida:12,atributo:'Força',armaduras:['Leve','Média','Escudos'],resistencias_teste:['Força','Constituição'],pericias:{n:2,lista:['Atletismo','Intimidação','Natureza','Percepção','Sobrevivência','Animais']},subclasses:['Caminho do Berserker','Caminho do Guerreiro Totêmico'],tabela:[{n:1,prof:2,carac:'Fúria 2x, Defesa sem Armadura'},{n:2,prof:2,carac:'Ataque Descuidado'},{n:3,prof:2,carac:'Caminho Primitivo, Fúria 3x'},{n:4,prof:2,carac:'Incremento de Atributo'},{n:5,prof:3,carac:'Ataque Extra, Mov. Rápido, Fúria 3x'},{n:9,prof:4,carac:'Crítico Brutal +1d'},{n:20,prof:6,carac:'Campeão Primitivo +4 FOR/CON'}]},
    {nome:'Bardo',dado_vida:8,atributo:'Carisma',armaduras:['Leve'],resistencias_teste:['Destreza','Carisma'],pericias:{n:3,lista:'Qualquer'},subclasses:['Colégio do Conhecimento','Colégio do Valor'],tabela:[{n:1,prof:2,carac:'Conjuração, Inspiração d6'},{n:2,prof:2,carac:'Canção de Descanso'},{n:3,prof:2,carac:'Colégio, Especialização'},{n:5,prof:3,carac:'Inspiração d8'},{n:10,prof:4,carac:'Segredos Mágicos'},{n:20,prof:6,carac:'Inspiração d12'}]},
    {nome:'Clérigo',dado_vida:8,atributo:'Sabedoria',armaduras:['Leve','Média','Escudos'],resistencias_teste:['Sabedoria','Carisma'],pericias:{n:2,lista:['História','Intuição','Medicina','Persuasão','Religião']},subclasses:['Vida','Luz','Guerra','Tempestade','Natureza','Conhecimento','Enganação'],tabela:[{n:1,prof:2,carac:'Conjuração, Domínio'},{n:2,prof:2,carac:'Canalizar Divindade 1x'},{n:5,prof:3,carac:'Destruir Mortos-Vivos'},{n:10,prof:4,carac:'Intervenção Divina'},{n:20,prof:6,carac:'Intervenção Divina Aperfeiçoada'}]},
    {nome:'Druida',dado_vida:8,atributo:'Sabedoria',armaduras:['Leve','Média'],resistencias_teste:['Inteligência','Sabedoria'],pericias:{n:2,lista:['Animais','Arcana','Medicina','Natureza','Percepção','Religião','Sobrevivência']},subclasses:['Círculo da Terra','Círculo da Lua'],tabela:[{n:1,prof:2,carac:'Druídico, Conjuração'},{n:2,prof:2,carac:'Forma Selvagem, Círculo'}]},
    {nome:'Guerreiro',dado_vida:10,atributo:'Força ou Destreza',armaduras:['Todas','Escudos'],resistencias_teste:['Força','Constituição'],pericias:{n:2,lista:['Acrobacia','Animais','Atletismo','História','Intuição','Intimidação','Percepção','Sobrevivência']},estilos:['Arqueria +2','Defesa +1CA','Duelo +2','Combate c/ Grandes Armas','Proteção','Duas Armas'],subclasses:['Campeão','Cavaleiro de Batalha','Cavaleiro Élfico'],tabela:[{n:1,prof:2,carac:'Estilo, Retomar o Fôlego'},{n:2,prof:2,carac:'Surto de Ação'},{n:3,prof:2,carac:'Arquétipo Marcial'},{n:5,prof:3,carac:'Ataque Extra'},{n:11,prof:4,carac:'Ataque Extra 3x'},{n:20,prof:6,carac:'Ataque Extra 4x'}]},
    {nome:'Ladino',dado_vida:8,atributo:'Destreza',armaduras:['Leve'],resistencias_teste:['Destreza','Inteligência'],pericias:{n:4,lista:['Acrobacia','Atletismo','Enganação','Furtividade','Intuição','Intimidação','Investigação','Percepção','Persuasão','Prestidigitação']},subclasses:['Assassino','Ladrão','Mago Arcano'],tabela:[{n:1,prof:2,carac:'Especialização, Furtivo 1d6'},{n:3,prof:2,carac:'Furtivo 2d6, Arquétipo'},{n:5,prof:3,carac:'Esquiva Sobrenatural, 3d6'},{n:11,prof:4,carac:'Talento Confiável, 6d6'},{n:20,prof:6,carac:'Furtivo 10d6'}]},
    {nome:'Mago',dado_vida:6,atributo:'Inteligência',armaduras:[],resistencias_teste:['Inteligência','Sabedoria'],pericias:{n:2,lista:['Arcana','História','Intuição','Investigação','Medicina','Religião']},subclasses:['Abjuração','Conjuração','Adivinhação','Encantamento','Evocação','Ilusão','Necromancia','Transmutação'],tabela:[{n:1,prof:2,carac:'Conjuração, Recuperação Arcana'},{n:2,prof:2,carac:'Tradição Arcana'},{n:18,prof:6,carac:'Maestria de Magia'},{n:20,prof:6,carac:'Assinatura de Magia'}]},
    {nome:'Monge',dado_vida:8,atributo:'Destreza e Sabedoria',armaduras:[],resistencias_teste:['Força','Destreza'],pericias:{n:2,lista:['Acrobacia','Atletismo','Furtividade','História','Intuição','Religião']},subclasses:['Mão Aberta','Quatro Elementos','Sombras'],tabela:[{n:1,prof:2,carac:'Defesa sem Armadura, Artes Marciais 1d4'},{n:2,prof:2,carac:'Chi 2pts, +3m'},{n:5,prof:3,carac:'Ataque Extra, 1d6'},{n:11,prof:4,carac:'1d8'},{n:20,prof:6,carac:'1d10'}]},
    {nome:'Paladino',dado_vida:10,atributo:'Força e Carisma',armaduras:['Todas','Escudos'],resistencias_teste:['Sabedoria','Carisma'],pericias:{n:2,lista:['Atletismo','Intuição','Intimidação','Medicina','Persuasão','Religião']},subclasses:['Devoção','Anciões','Vingança'],tabela:[{n:1,prof:2,carac:'Sentido Divino, Cura pelas Mãos'},{n:2,prof:2,carac:'Estilo, Conjuração, Destruição 2d8'},{n:3,prof:2,carac:'Juramento'},{n:5,prof:3,carac:'Ataque Extra'},{n:20,prof:6,carac:'Destruição 6d8'}]},
    {nome:'Patrulheiro',dado_vida:10,atributo:'Destreza e Sabedoria',armaduras:['Leve','Média','Escudos'],resistencias_teste:['Força','Destreza'],pericias:{n:3,lista:['Animais','Atletismo','Intuição','Investigação','Natureza','Percepção','Furtividade','Sobrevivência']},subclasses:['Caçador','Mestre das Bestas'],tabela:[{n:1,prof:2,carac:'Inimigo Favorito, Explorador Natural'},{n:2,prof:2,carac:'Estilo, Conjuração'},{n:5,prof:3,carac:'Ataque Extra'},{n:20,prof:6,carac:'Inimigo Supremo'}]},
    {nome:'Bruxo',dado_vida:8,atributo:'Carisma',armaduras:['Leve'],resistencias_teste:['Sabedoria','Carisma'],pericias:{n:2,lista:['Arcana','Enganação','História','Intimidação','Investigação','Natureza','Religião']},subclasses:['Arquifada','Imundo','Grande Ancião'],tabela:[{n:1,prof:2,carac:'Patrono, Pacto'},{n:2,prof:2,carac:'Invocações'},{n:3,prof:2,carac:'Dádiva do Pacto'},{n:11,prof:4,carac:'Segredos Místicos'},{n:20,prof:6,carac:'Segredos Extra'}]},
    {nome:'Feiticeiro',dado_vida:6,atributo:'Carisma',armaduras:[],resistencias_teste:['Constituição','Carisma'],pericias:{n:2,lista:['Arcana','Enganação','Intuição','Intimidação','Persuasão','Religião']},subclasses:['Origem Dracônica','Magia Selvagem'],tabela:[{n:1,prof:2,carac:'Conjuração, Origem'},{n:2,prof:2,carac:'Fonte de Magia 2pts'},{n:3,prof:2,carac:'Metamágica'},{n:20,prof:6,carac:'Restauração da Feitiçaria'}]},
  ],

  pericias: [
    {nome:'Acrobacia',atributo:'des'},{nome:'Animais',atributo:'sab'},{nome:'Arcana',atributo:'int'},
    {nome:'Atletismo',atributo:'for'},{nome:'Atuação',atributo:'car'},{nome:'Enganação',atributo:'car'},
    {nome:'Furtividade',atributo:'des'},{nome:'História',atributo:'int'},{nome:'Intimidação',atributo:'car'},
    {nome:'Intuição',atributo:'sab'},{nome:'Investigação',atributo:'int'},{nome:'Medicina',atributo:'sab'},
    {nome:'Natureza',atributo:'int'},{nome:'Percepção',atributo:'sab'},{nome:'Persuasão',atributo:'car'},
    {nome:'Prestidigitação',atributo:'des'},{nome:'Religião',atributo:'int'},{nome:'Sobrevivência',atributo:'sab'},
  ],

  monstros: [
    {nome:'Goblin',tipo:'Humanoide Pequeno',ca:15,pv:7,pv_dado:'2d6',mov:9,for:8,des:14,con:10,int:10,sab:8,car:8,nd:'1/4',xp:50,acoes:[{nome:'Cimitarra',bonus:'+4',dano:'1d6+2 cortante'},{nome:'Arco Curto',bonus:'+4',alcance:'24/96m',dano:'1d6+2 perfurante'}]},
    {nome:'Orc',tipo:'Humanoide Médio',ca:13,pv:15,pv_dado:'2d8+6',mov:9,for:16,des:12,con:16,int:7,sab:11,car:10,nd:'1/2',xp:100,acoes:[{nome:'Machadão',bonus:'+5',dano:'1d12+3 cortante'},{nome:'Azagaia',bonus:'+5',dano:'1d6+3 perfurante'}]},
    {nome:'Esqueleto',tipo:'Morto-vivo Médio',ca:13,pv:13,pv_dado:'2d8+4',mov:9,for:10,des:14,con:15,int:6,sab:8,car:5,nd:'1/4',xp:50,imunidades:['veneno','exaustão'],vulnerabilidades:['concussão'],acoes:[{nome:'Cimitarra',bonus:'+4',dano:'1d6+2 cortante'},{nome:'Arco Curto',bonus:'+4',dano:'1d6+2 perfurante'}]},
    {nome:'Zumbi',tipo:'Morto-vivo Médio',ca:8,pv:22,pv_dado:'3d8+9',mov:6,for:13,des:6,con:16,int:3,sab:6,car:5,nd:'1/4',xp:50,tracos:['Resiliência Mórbida CD 5+dano'],acoes:[{nome:'Golpe',bonus:'+3',dano:'1d6+1 concussão'}]},
    {nome:'Lobo',tipo:'Besta Médio',ca:12,pv:11,pv_dado:'2d8+2',mov:12,for:12,des:15,con:12,int:3,sab:12,car:6,nd:'1/4',xp:50,tracos:['Olfato Aguçado','Táticas de Matilha (vantagem)'],acoes:[{nome:'Mordida',bonus:'+4',dano:'2d4+2 perfurante',extra:'CD 11 FOR ou derrubado'}]},
    {nome:'Gnoll',tipo:'Humanoide Médio',ca:15,pv:22,pv_dado:'5d8',mov:9,for:14,des:12,con:11,int:6,sab:10,car:7,nd:'1/2',xp:100,tracos:['Frenesi Rastejante'],acoes:[{nome:'Mordida',bonus:'+4',dano:'1d4+2'},{nome:'Lança',bonus:'+4',dano:'1d6+2'}]},
    {nome:'Kobold',tipo:'Humanoide Pequeno',ca:12,pv:5,pv_dado:'2d6-2',mov:9,for:7,des:15,con:9,int:8,sab:7,car:8,nd:'1/8',xp:25,tracos:['Sensibilidade Luz Solar','Táticas de Matilha'],acoes:[{nome:'Adaga',bonus:'+4',dano:'1d4+2'},{nome:'Funda',bonus:'+4',dano:'1d4+2'}]},
    {nome:'Bugbear',tipo:'Humanoide Médio',ca:16,pv:27,pv_dado:'5d8+5',mov:9,for:15,des:14,con:13,int:8,sab:11,car:9,nd:'1',xp:200,tracos:['Surpresa Brutal +2d6'],acoes:[{nome:'Maça',bonus:'+4',dano:'2d6+2'},{nome:'Azagaia',bonus:'+4',dano:'2d6+2'}]},
    {nome:'Ogro',tipo:'Gigante Grande',ca:11,pv:59,pv_dado:'7d10+21',mov:12,for:19,des:8,con:16,int:5,sab:7,car:7,nd:'2',xp:450,acoes:[{nome:'Maça Larga',bonus:'+6',dano:'2d8+4'},{nome:'Azagaia',bonus:'+6',dano:'2d6+4'}]},
    {nome:'Troll',tipo:'Gigante Grande',ca:15,pv:84,pv_dado:'8d10+40',mov:9,for:18,des:13,con:20,int:7,sab:9,car:7,nd:'5',xp:1800,tracos:['Regeneração 10 PV/turno (exc. ácido/fogo)','Olfato Aguçado'],acoes:[{nome:'Mordida',bonus:'+7',dano:'1d6+4'},{nome:'Garra',bonus:'+7',dano:'2d6+4'}]},
    {nome:'Múmia',tipo:'Morto-vivo Médio',ca:11,pv:58,pv_dado:'9d8+18',mov:6,for:16,des:8,con:15,int:6,sab:10,car:12,nd:'3',xp:700,vulnerabilidades:['fogo'],acoes:[{nome:'Soco Apodrecido',bonus:'+5',dano:'2d6+3 + 3d6 necrótico'},{nome:'Olhar Assustador',cd:'CD 11 SAB'}]},
    {nome:'Vampiro',tipo:'Morto-vivo Médio',ca:16,pv:144,pv_dado:'17d8+68',mov:9,for:18,des:18,con:18,int:17,sab:15,car:18,nd:'13',xp:10000,tracos:['Regeneração 20PV/turno','Sensibilidade à Luz Solar'],acoes:[{nome:'Aperto',bonus:'+9',dano:'2d6+4 + agarrado'},{nome:'Mordida',bonus:'+9',dano:'1d6+4 + 3d6 necrótico (cura=dano)'}]},
    {nome:'Dragão Vermelho Jovem',tipo:'Dragão Grande',ca:18,pv:178,pv_dado:'17d10+85',mov:'12m, voo 24m',for:23,des:10,con:21,int:14,sab:11,car:19,nd:'13',xp:10000,imunidades:['fogo'],acoes:[{nome:'Mordida',bonus:'+10',dano:'2d10+6 + 1d6 fogo'},{nome:'Sopro de Fogo',cd:'CD 19 DES',area:'Cone 9m',dano:'16d6 fogo',recarga:'5-6'}]},
    {nome:'Dragão Vermelho Ancião',tipo:'Dragão Enorme',ca:22,pv:546,pv_dado:'28d20+252',mov:'12m, voo 24m',for:30,des:10,con:29,int:18,sab:15,car:23,nd:'24',xp:62000,imunidades:['fogo'],acoes:[{nome:'Mordida',bonus:'+17',dano:'2d10+10 + 4d6 fogo'},{nome:'Sopro de Fogo',cd:'CD 24 DES',area:'Cone 18m',dano:'26d6 fogo'}]},
    {nome:'Lich',tipo:'Morto-vivo Médio',ca:17,pv:135,pv_dado:'18d8+54',mov:9,for:11,des:16,con:16,int:20,sab:14,car:16,nd:'21',xp:33000,tracos:['Resistência Lendária 3/dia','Filactéria: retorna 1d10 dias'],acoes:[{nome:'Toque Paralisante',bonus:'+12',dano:'3d6 frio, CD 18 CON paralisado'},{nome:'Arco de Relâmpago',alcance:'36m',dano:'4d6 raio'}]},
    {nome:'Manticora',tipo:'Monstruosidade Grande',ca:14,pv:68,pv_dado:'8d10+24',mov:'9m, voo 18m',for:17,des:16,con:17,int:7,sab:11,car:8,nd:'3',xp:700,acoes:[{nome:'Mordida',bonus:'+5',dano:'1d8+3'},{nome:'Espinhos',bonus:'+5',alcance:'9/18m',dano:'2d4+3',qtd:3}]},
    {nome:'Monstro da Ferrugem',tipo:'Monstruosidade Média',ca:14,pv:27,pv_dado:'5d8+5',mov:12,for:13,des:12,con:13,int:2,sab:13,car:6,nd:'1/2',xp:100,tracos:['Corrói metais no toque'],acoes:[{nome:'Tentáculo',bonus:'+3',extra:'Corrói metal tocado'},{nome:'Mordida',bonus:'+3',dano:'1d8+1'}]},
    {nome:'Hobgoblin',tipo:'Humanoide Médio',ca:18,pv:11,pv_dado:'2d8+2',mov:9,for:13,des:12,con:12,int:10,sab:10,car:9,nd:'1/2',xp:100,tracos:['Formação Marcial (+1 ataque c/ aliado adj)'],acoes:[{nome:'Espada Longa',bonus:'+3',dano:'1d8+1'},{nome:'Arco Longo',bonus:'+3',alcance:'45/180m',dano:'1d8+1'}]},
  ],

  magias: [
    {nome:'Globos de Luz',nivel:0,escola:'Evocação',classes:['Bardo','Clérigo','Mago'],alcance:'18m',duracao:'Conc. 1min',descricao:'Esfera brilhante de 30cm flutuante.'},
    {nome:'Choque do Trovão',nivel:0,escola:'Evocação',classes:['Druida','Mago','Feiticeiro','Bruxo'],alcance:'Toque',descricao:'1d8 raio, afasta 3m. +1d8 por patamar.'},
    {nome:'Fogo Sagrado',nivel:0,escola:'Evocação',classes:['Clérigo'],alcance:'18m',descricao:'CD SAB ou 1d8 radiante. +1d8/patamar.'},
    {nome:'Raio de Gelo',nivel:0,escola:'Evocação',classes:['Mago','Feiticeiro'],alcance:'18m',descricao:'Ataque: 1d8 frio + velocidade 0.'},
    {nome:'Prestidigitação',nivel:0,escola:'Transmutação',classes:['Bardo','Feiticeiro','Bruxo','Mago'],alcance:'3m',descricao:'Efeitos mágicos menores.'},
    {nome:'Zombaria Viciosa',nivel:0,escola:'Encantamento',classes:['Bardo'],alcance:'18m',descricao:'CD INT ou 1d4 psíquico + desvantagem.'},
    {nome:'Cura Ferimentos',nivel:1,escola:'Evocação',classes:['Bardo','Clérigo','Druida','Paladino','Patrulheiro'],alcance:'Toque',descricao:'1d8+mod PV. +1d8/espaço.'},
    {nome:'Míssil Mágico',nivel:1,escola:'Evocação',classes:['Feiticeiro','Mago'],alcance:'36m',descricao:'3 dardos 1d4+1, acerto auto. +1 dardo/espaço.'},
    {nome:'Escudo',nivel:1,escola:'Abjuração',classes:['Feiticeiro','Mago'],tempo:'1 reação',descricao:'+5 CA até próximo turno. Anula Míssil Mágico.'},
    {nome:'Dormir',nivel:1,escola:'Encantamento',classes:['Bardo','Feiticeiro','Mago'],alcance:'27m',descricao:'5d8 PV adormecidos (mais fracos primeiro).'},
    {nome:'Detectar Magia',nivel:1,escola:'Adivinhação',classes:['Bardo','Clérigo','Druida','Paladino','Feiticeiro','Mago'],descricao:'Sente magia em 18m por 10 min.'},
    {nome:'Bênção',nivel:1,escola:'Encantamento',classes:['Clérigo','Paladino'],descricao:'3 criaturas: +1d4 em ataques e resistências.'},
    {nome:'Mãos Flamejantes',nivel:1,escola:'Evocação',classes:['Feiticeiro','Mago'],alcance:'Cone 4,5m',descricao:'CD DES ou 3d6 fogo. +1d6/espaço.'},
    {nome:'Armadura Mágica',nivel:1,escola:'Abjuração',classes:['Feiticeiro','Mago'],descricao:'CA = 13+DES (sem armadura). 8 horas.'},
    {nome:'Invisibilidade',nivel:2,escola:'Ilusão',classes:['Bardo','Feiticeiro','Bruxo','Mago'],descricao:'Invisível por 1h. +1 criatura/espaço.'},
    {nome:'Raio Ardente',nivel:2,escola:'Evocação',classes:['Feiticeiro','Mago'],alcance:'27m',descricao:'3 raios 2d6 fogo. +1 raio/espaço.'},
    {nome:'Silêncio',nivel:2,escola:'Ilusão',classes:['Bardo','Clérigo','Patrulheiro'],descricao:'Esfera 6m sem som por 10 min.'},
    {nome:'Palavra Curativa',nivel:1,escola:'Evocação',classes:['Bardo','Clérigo','Druida'],tempo:'1 ação bônus',alcance:'18m',descricao:'1d4+mod PV à distância.'},
    {nome:'Bola de Fogo',nivel:3,escola:'Evocação',classes:['Feiticeiro','Mago'],alcance:'45m',descricao:'CD DES ou 8d6 fogo em raio 6m. +1d6/espaço.'},
    {nome:'Relâmpago',nivel:3,escola:'Evocação',classes:['Feiticeiro','Mago'],alcance:'Linha 30m',descricao:'CD DES ou 8d6 raio. +1d6/espaço.'},
    {nome:'Voo',nivel:3,escola:'Transmutação',classes:['Feiticeiro','Bruxo','Mago'],descricao:'Voo 18m por 10 min. +1 criatura/espaço.'},
    {nome:'Revivificar',nivel:3,escola:'Necromancia',classes:['Clérigo','Paladino'],descricao:'Ressuscita morto <1 min com 1 PV.'},
    {nome:'Contramágica',nivel:3,escola:'Abjuração',classes:['Feiticeiro','Bruxo','Mago'],tempo:'1 reação',alcance:'18m',descricao:'Anula magia ≤3°. Para ≥4°: CD 10+nível INT.'},
    {nome:'Cone de Frio',nivel:5,escola:'Evocação',classes:['Feiticeiro','Mago'],alcance:'Cone 18m',descricao:'CD CON ou 8d8 frio. +1d8/espaço.'},
    {nome:'Ressurreição',nivel:5,escola:'Necromancia',classes:['Bardo','Clérigo'],descricao:'Ressuscita morto <100 anos.'},
  ],

  itens_magicos: [
    {nome:'Poção de Cura',raridade:'Comum',tipo:'Poção',descricao:'2d4+2 PV.'},
    {nome:'Poção de Cura Superior',raridade:'Incomum',tipo:'Poção',descricao:'4d4+4 PV.'},
    {nome:'Poção de Cura Grande',raridade:'Raro',tipo:'Poção',descricao:'8d4+8 PV.'},
    {nome:'Poção de Invisibilidade',raridade:'Muito Raro',tipo:'Poção',descricao:'Invisibilidade 1h.'},
    {nome:'Espada Longa +1',raridade:'Incomum',tipo:'Arma',descricao:'+1 ataques e dano.'},
    {nome:'Espada Longa +2',raridade:'Raro',tipo:'Arma',descricao:'+2 ataques e dano.'},
    {nome:'Espada Longa +3',raridade:'Muito Raro',tipo:'Arma',descricao:'+3 ataques e dano.'},
    {nome:'Capa de Proteção',raridade:'Incomum',tipo:'Maravilhoso',sintonia:true,descricao:'+1 CA e resistências.'},
    {nome:'Anel de Proteção',raridade:'Raro',tipo:'Anel',sintonia:true,descricao:'+1 CA e resistências.'},
    {nome:'Botas de Velocidade',raridade:'Raro',tipo:'Maravilhoso',sintonia:true,descricao:'Dobra velocidade.'},
    {nome:'Amuleto da Saúde',raridade:'Raro',tipo:'Maravilhoso',sintonia:true,descricao:'CON = 19.'},
    {nome:'Bastão dos Magos',raridade:'Raro',tipo:'Cajado',descricao:'+2 ataques/CD, 10 cargas de magias.'},
    {nome:'Elmo do Brilho',raridade:'Muito Raro',tipo:'Maravilhoso',sintonia:true,descricao:'Raio de sol, Luz, Fogo Sagrado.'},
    {nome:'Capa do Deslocamento',raridade:'Raro',tipo:'Maravilhoso',sintonia:true,descricao:'Desvantagem em ataques contra você.'},
    {nome:'Braçadeiras de Defesa',raridade:'Raro',tipo:'Maravilhoso',sintonia:true,descricao:'CA = 13+DES sem armadura.'},
  ],

  regras: {
    iniciativa:'D20 + mod.Destreza.',
    acoes:['Ataque','Conjurar Magia','Dash','Desengajar','Esquivar','Ajudar','Esconder','Preparar','Usar Objeto'],
    critico:'20 natural: dobrar todos os dados de dano.',
    fumble:'1 natural: falha automática.',
    ataque_oportunidade:'Criatura sai do alcance sem Desengajar.',
    condicoes:{
      Agarrado:'Velocidade 0.',Assustado:'Desvantagem enquanto ver a fonte.',
      Atordoado:'Incapaz, falha FOR/DES, ataques com vantagem.',
      Caido:'Desvantagem att. Adj tem vantagem. Levantar = 1/2 mov.',
      Cego:'Desvantagem att, atacado com vantagem.',Enfeitiçado:'Não ataca conjurador.',
      Envenenado:'Desvantagem ataques e testes.',Invisivel:'Vantagem att, desvantagem contra.',
      Paralisado:'Incapaz, falha FOR/DES, crítico automático adj.',
    },
    descanso_curto:'1 hora. Gastar Dados de Vida para recuperar PV.',
    descanso_longo:'8 horas. Todos PV, metade Dados de Vida, todos recursos.',
    testes_morte:'3 falhas = morte. 3 sucessos = estabilizado. 20 = 1 PV.',
    xp_por_nivel:{1:0,2:300,3:900,4:2700,5:6500,6:14000,7:23000,8:34000,9:48000,10:64000,11:85000,12:100000,13:120000,14:140000,15:165000,16:195000,17:225000,18:265000,19:305000,20:355000},
    bonus_proficiencia:{1:2,2:2,3:2,4:2,5:3,6:3,7:3,8:3,9:4,10:4,11:4,12:4,13:5,14:5,15:5,16:5,17:6,18:6,19:6,20:6},
  },

  calcMod(v){return Math.floor((v-10)/2)},
  calcNivel(xp){const t=Object.values(this.regras.xp_por_nivel);for(let i=t.length-1;i>=0;i--)if(xp>=t[i])return i+1;return 1},
  getMonstro(nome){return this.monstros.find(m=>m.nome.toLowerCase().includes(nome.toLowerCase()))},
  getClasse(nome){return this.classes.find(c=>c.nome.toLowerCase().includes(nome.toLowerCase()))},
  getRaca(nome){return this.racas.find(r=>r.nome.toLowerCase().includes(nome.toLowerCase()))},
  getMagia(nome){return this.magias.find(m=>m.nome.toLowerCase().includes(nome.toLowerCase()))},
};

if(typeof module!=='undefined')module.exports=DND5E;
